### ISSUE TITLE
Recent commits to servolux break this gem

### ISSUE THREAD

**Issue by miketheman** [papertrail/remote_syslog#89]
I know it's deprecated, however a recent change to the gem's dependency has broken this gem like so:

    lib/ruby/gems/1.9.1/gems/remote_syslog-1.6.14/lib/remote_syslog/cli.rb:185:in `basename': can't convert Servolux::PidFile into String (TypeError)

A solution we found was to install servolux version 0.10.0 _before_ installing remote_syslog gem, as there's no pinning of dependency at all in this gem.

**Comment by troy** [comment]
If you're going to bother, [install remote_syslog2](https://github.com/papertrail/remote_syslog2).

If you elect not to, can you tell me why you're sticking with the old one? It's inferior in every way I know of.

**Comment by miketheman** [comment]
@troy We've been using the gem here quite successfully for the past 3 years, and today it broke due to a dep not being pinned.

We're going to kick off a replacement for this with the newer daemon, that's not going to happen immediately across a widely-deployed infrastructure.

I'm not suggesting you spend time fixing this issue, rather it will likely come up with any other users of the gem, so this can be searched and found.

I'd recommend two things:

1. update this gem's dependencies to lock it to no newer than servolux 0.10.0 and release
1. update https://rubygems.org/gems/remote_syslog with a note on the deprecation status, as this was the first place our team looked to for cause of breakage.

**Comment by eric** [comment]
I've released 1.6.15 that locks the servolux dependency. Let me know if you run into any issues with it.

**Comment by miketheman** [comment]
Thanks @eric !
